"""add subtitle_url to raw_content_items

Revision ID: 1b0f95a14e99
Revises: 9ab484712cc9
Create Date: 2026-05-03 20:00:53.301252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b0f95a14e99'
down_revision: Union[str, Sequence[str], None] = '9ab484712cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_content_items', sa.Column('subtitle_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_content_items', 'subtitle_url')
    # ### end Alembic commands ###
