"""initial tables

Revision ID: 1d2adbac0466
Revises: 
Create Date: 2026-02-22 15:14:03.271175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2adbac0466'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('niches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('hashtag_seeds', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_niches_name'), 'niches', ['name'], unique=True)
    op.create_table('detected_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=True),
    sa.Column('trend_type', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('velocity_score', sa.Float(), nullable=False),
    sa.Column('supporting_content_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_trends_created_at'), 'detected_trends', ['created_at'], unique=False)
    op.create_index(op.f('ix_detected_trends_label'), 'detected_trends', ['label'], unique=False)
    op.create_index(op.f('ix_detected_trends_niche_id'), 'detected_trends', ['niche_id'], unique=False)
    op.create_index(op.f('ix_detected_trends_status'), 'detected_trends', ['status'], unique=False)
    op.create_index(op.f('ix_detected_trends_trend_type'), 'detected_trends', ['trend_type'], unique=False)
    op.create_table('raw_content_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('platform_content_id', sa.String(length=128), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('audio_id', sa.String(length=255), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('duration_in_seconds', sa.Integer(), nullable=True),
    sa.Column('content_format', sa.String(length=50), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_content_id', name='uniq_raw_platform_content_id')
    )
    op.create_index(op.f('ix_raw_content_items_collected_at'), 'raw_content_items', ['collected_at'], unique=False)
    op.create_index(op.f('ix_raw_content_items_content_format'), 'raw_content_items', ['content_format'], unique=False)
    op.create_index(op.f('ix_raw_content_items_niche_id'), 'raw_content_items', ['niche_id'], unique=False)
    op.create_index(op.f('ix_raw_content_items_platform'), 'raw_content_items', ['platform'], unique=False)
    op.create_index(op.f('ix_raw_content_items_published_at'), 'raw_content_items', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_content_items_published_at'), table_name='raw_content_items')
    op.drop_index(op.f('ix_raw_content_items_platform'), table_name='raw_content_items')
    op.drop_index(op.f('ix_raw_content_items_niche_id'), table_name='raw_content_items')
    op.drop_index(op.f('ix_raw_content_items_content_format'), table_name='raw_content_items')
    op.drop_index(op.f('ix_raw_content_items_collected_at'), table_name='raw_content_items')
    op.drop_table('raw_content_items')
    op.drop_index(op.f('ix_detected_trends_trend_type'), table_name='detected_trends')
    op.drop_index(op.f('ix_detected_trends_status'), table_name='detected_trends')
    op.drop_index(op.f('ix_detected_trends_niche_id'), table_name='detected_trends')
    op.drop_index(op.f('ix_detected_trends_label'), table_name='detected_trends')
    op.drop_index(op.f('ix_detected_trends_created_at'), table_name='detected_trends')
    op.drop_table('detected_trends')
    op.drop_index(op.f('ix_niches_name'), table_name='niches')
    op.drop_table('niches')
    # ### end Alembic commands ###
