"""add extractor_responses table

Revision ID: 371ad2811047
Revises: c80c0f3460ea
Create Date: 2026-05-12 16:29:00.299873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371ad2811047'
down_revision: Union[str, Sequence[str], None] = 'c80c0f3460ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extractor_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_item_id', sa.Integer(), nullable=False),
    sa.Column('prompt_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('envelope', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('usage_input_tokens', sa.Integer(), nullable=True),
    sa.Column('usage_output_tokens', sa.Integer(), nullable=True),
    sa.Column('usage_cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['raw_content_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_item_id', 'prompt_fingerprint', name='uniq_extractor_response_item_fingerprint')
    )
    op.create_index(op.f('ix_extractor_responses_content_item_id'), 'extractor_responses', ['content_item_id'], unique=False)
    op.create_index(op.f('ix_extractor_responses_prompt_fingerprint'), 'extractor_responses', ['prompt_fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extractor_responses_prompt_fingerprint'), table_name='extractor_responses')
    op.drop_index(op.f('ix_extractor_responses_content_item_id'), table_name='extractor_responses')
    op.drop_table('extractor_responses')
    # ### end Alembic commands ###
