"""blueprint foundation

Revision ID: 9ab484712cc9
Revises: 2b8da12d6923
Create Date: 2026-05-02 18:33:01.339855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab484712cc9'
down_revision: Union[str, Sequence[str], None] = '2b8da12d6923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blueprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_item_id', sa.Integer(), nullable=False),
    sa.Column('extractor_version', sa.String(length=20), nullable=False),
    sa.Column('extractor_model', sa.String(length=100), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('blueprint_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['raw_content_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_item_id', 'extractor_version', name='uniq_blueprint_content_extractor_version')
    )
    op.create_index(op.f('ix_blueprints_content_item_id'), 'blueprints', ['content_item_id'], unique=False)
    op.create_index(op.f('ix_blueprints_extractor_version'), 'blueprints', ['extractor_version'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_item_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['raw_content_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_item_id', name='uniq_transcript_content_item')
    )
    op.create_index(op.f('ix_transcripts_content_item_id'), 'transcripts', ['content_item_id'], unique=True)
    op.add_column('raw_content_items', sa.Column('title', sa.Text(), nullable=True))
    op.add_column('raw_content_items', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('raw_content_items', sa.Column('thumbnail_url', sa.Text(), nullable=True))
    op.add_column('raw_content_items', sa.Column('video_url', sa.Text(), nullable=True))
    op.add_column('raw_content_items', sa.Column('author_username', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_raw_content_items_author_username'), 'raw_content_items', ['author_username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_content_items_author_username'), table_name='raw_content_items')
    op.drop_column('raw_content_items', 'author_username')
    op.drop_column('raw_content_items', 'video_url')
    op.drop_column('raw_content_items', 'thumbnail_url')
    op.drop_column('raw_content_items', 'description')
    op.drop_column('raw_content_items', 'title')
    op.drop_index(op.f('ix_transcripts_content_item_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_blueprints_extractor_version'), table_name='blueprints')
    op.drop_index(op.f('ix_blueprints_content_item_id'), table_name='blueprints')
    op.drop_table('blueprints')
    # ### end Alembic commands ###
